# Generated by Django 4.0.2 on 2022-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='cart.Order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
