# Generated by Django 4.0.2 on 2022-02-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание товара')),
                ('price_now', models.FloatField(verbose_name='Текущая цена товара')),
                ('price_old', models.FloatField(blank=True, null=True, verbose_name='Старая цена товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Колличество товара на складе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото пользователя')),
                ('status', models.CharField(choices=[('Have', 'Есть в наличие'), ('Havent', 'Временно отсутствует')], default='Have', max_length=15, verbose_name='Стаус товара')),
                ('discount', models.BooleanField(verbose_name='Cкидка на товар')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_ad', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
